doc/predefined-functions.asciidoc, src/main/java/gololang/Predefined.java
There are cases when one needs typed arrays, not just Object[] arrays.
This function wraps java.lang.reflect.Array.newInstance for that.
=> newTypedArray function

src/test/java/fr/insalyon/citi/golo/compiler/CompileAndRunTest.java, src/test/java/gololang/PredefinedTest.java
See #241
The warnings in tests compilation were due to:
- tests on deprecated Predefined golo functions;
- raw casts in range tests.
In both cases, it is safe to suppress them.
Also make some code cleaning.
=> Suppress warnings in tests.

src/main/java/fr/insalyon/citi/golo/compiler/utils/NamingUtils.java, src/main/jjtree/Golo.jjt
add an 'invalid' token to avoid TokenMgrError when " or - characters are typed in netbeans. Check not null parameter to avoid NullPointerException when user add an import statement
=> add 'invalid' token

src/main/java/gololang/Tuple.java, src/test/java/gololang/TupleTest.java
`Tuple` now implements `Comparable<Tuple>`. The comparison is done
pairwise, using lexicographical order, such that `[1, 2] < [1, 3]`
and `["b", 5] < ["d", 1]`.
=> Makes Tuple object comparable.

src/main/java/fr/insalyon/citi/golo/compiler/JavaBytecodeGenerationGoloIrVisitor.java, src/main/java/fr/insalyon/citi/golo/compiler/ParseTreeToGoloIrVisitor.java, src/main/java/fr/insalyon/citi/golo/runtime/OperatorType.java, src/main/jjtree/Golo.jjt, src/test/java/fr/insalyon/citi/golo/compiler/CompileAndRunTest.java, src/test/resources/for-execution/direct-anon-call.golo
As described in #219, it was impossible to directly call a anonymous function, as in
`(|x| -> x + 1)(1)`
This is fixed by allowing `AnonymousFunctionInvocation` in an
`AssociativeExpression` in the parser.
This change generates `BinaryOperation` with empty operator that must
thus be checked.
=> Fix Bug #219.

src/main/java/fr/insalyon/citi/golo/cli/Main.java
With the command 'version' and the option '--full',
this print the actual golo full version and the JVM version.
For example :
```
Golo version : 2.1.0-SNAPSHOT (build 15-03-15-12:34)
JVM version: 1.8.0_31
```
=> Print JVM version from command line 'version'

src/main/java/fr/insalyon/citi/golo/cli/Main.java, src/test/java/fr/insalyon/citi/golo/cli/MainTest.java
During a project creation with 'new' command line,
if a project name contains a non-word caracter,
they are escape into the dot caracter to avoid a compilation failure.
=> Escape module name during project creation to avoid a compilation failure

doc/closures.asciidoc, src/test/java/fr/insalyon/citi/golo/compiler/CompileAndRunTest.java, src/test/resources/for-execution/direct-anon-call.golo
This PR fixes some oversight in PR #247
- adds a few tests on direct anonymous function call when the function
is returned by a method invocation
- change the doc accordingly, since now the warning in the
“calling functions that return functions” section is no longer valid
=> Fix tests and doc of anonymous function call.

src/main/java/gololang/FunctionReference.java, src/test/java/gololang/FunctionReferenceTest.java
Checks that the function argument takes exactly 1 parameter.
Interestingly, the composition of method handles with filterReturnValue and mismatching
types is possible, and provokes a SIGSEGV of the JVM at runtime.
Fix for #262
Signed-off-by: Julien Ponge <julien.ponge@insa-lyon.fr>
=> Check andThen function parameter arity

src/main/java/fr/insalyon/citi/golo/cli/Main.java, src/main/java/fr/insalyon/citi/golo/cli/command/CompilerCommand.java, src/main/java/fr/insalyon/citi/golo/cli/command/DiagnoseCommand.java, src/main/java/fr/insalyon/citi/golo/cli/command/DocCommand.java, src/main/java/fr/insalyon/citi/golo/cli/command/GoloGoloCommand.java, src/main/java/fr/insalyon/citi/golo/cli/command/InitCommand.java, src/main/java/fr/insalyon/citi/golo/cli/command/Metadata.java, src/main/java/fr/insalyon/citi/golo/cli/command/RunCommand.java, src/main/java/fr/insalyon/citi/golo/cli/command/VersionCommand.java, src/main/java/fr/insalyon/citi/golo/cli/command/spi/CliCommand.java, src/main/resources/META-INF/services/fr.insalyon.citi.golo.cli.command.spi.CliCommand
Internally the cli configuration is done with the Service Provider API.
Now, all classes who implements `CliCommand` and are declared as implementation for the service provider API are added to the cli automatically.
All current sub-commands implements `CliCommand`.
=> Ease the creation of others sub-commands for cli

doc/decorators.asciidoc, src/main/java/fr/insalyon/citi/golo/compiler/JavaBytecodeGenerationGoloIrVisitor.java, src/main/java/fr/insalyon/citi/golo/compiler/ParseTreeToGoloIrVisitor.java, src/main/java/fr/insalyon/citi/golo/compiler/ir/GoloFunction.java, src/main/java/fr/insalyon/citi/golo/compiler/parser/ASTFunctionDeclaration.java, src/main/java/fr/insalyon/citi/golo/runtime/AugmentationMethodFinder.java, src/main/java/fr/insalyon/citi/golo/runtime/DecoratorsHelper.java, src/main/java/fr/insalyon/citi/golo/runtime/FunctionCallSupport.java, src/main/java/fr/insalyon/citi/golo/runtime/RegularMethodFinder.java, src/main/java/gololang/DecoratedBy.java, src/main/java/gololang/Predefined.java, src/main/java/gololang/annotations/DecoratedBy.java, src/main/java/gololang/annotations/package-info.java, src/test/java/fr/insalyon/citi/golo/compiler/CompileAndRunTest.java, src/test/resources/for-execution/bang.golo, src/test/resources/for-execution/decorators.golo
It is not currently possible to change the
the arity of a decorated function.
( see https://gist.github.com/yloiseau/d669c0e30023bf5b5bbc )
Originaly the function `foo`:
```golo
module curry
function curry = |f| -> |a| -> |b| -> f(a, b)
@curry
function foo = |a,b| -> a + b
```
is converted to :
```golo
module curry
function curry = |f| -> |a| -> |b| -> f(a, b)
function foo = |a,b| -> ^curry( |a, b| -> a + b )(a, b)
```
The trick tranforms the original function in a
variable arity function like this :
```golo
module curry
function curry = |f| -> |a| -> |b| -> f(a, b)
function foo = |args...| -> ^curry( |a, b| -> a + b ): invokeWithArguments(args)
```
=> Change the original function arity with decorators

src/main/golo/standard-augmentations.golo, src/test/java/gololang/StandardAugmentationsTest.java, src/test/resources/for-test/bootstrapped-standard-augmentations.golo
Since `Tuple` and `List` have both a `get` method the `join` algo can be extracted and mutualized. 
This is a quick, naive and dirty workaround fo #268 .
=> Refactoring the augmented join method

doc/closures.asciidoc, src/main/java/gololang/FunctionReference.java, src/main/java/gololang/Predefined.java, src/test/java/fr/insalyon/citi/golo/compiler/CompileAndRunTest.java, src/test/resources/for-execution/closures.golo
This allows `gololang.Predefined::fun` to retrieve non-static methods,
and so to access unbound methods. It is now possible to write:
```golo
list["Foo", "Bar", "Hello", "Goodbye"]
: filter(^String::endsWith: bindAt(1, "o"))
```
instead of
```golo
list["Foo", "Bar", "Hello", "Goodbye"]
: filter(|s| -> s: endsWith("o"))
```
or
```golo
list["Foo", "Bar", "Hello", "Goodbye"]
: map(^String::length)
```
Also fixes a NPE on named parameters in `FunctionReference`.
=> Allows `fun` to retrieve non-static methods.

src/main/java/fr/insalyon/citi/golo/runtime/FunctionCallSupport.java, src/test/java/fr/insalyon/citi/golo/compiler/CompileAndRunTest.java, src/test/resources/for-execution/java8-lambda.golo
This PR fixes bug #273.
We had a problem when adapting a Golo closure to a Java8 lambda, when
the required functional interface returns a primitive type. This
appears for instance when using `Stream::filter`, since
`Predicate::test` returns a `boolean`.
Fixed by forcing the implemented signature in the `metafactory` to the required one.
=> Fix bug #273.

doc/control-flow.asciidoc, samples/echo-args.golo, src/main/java/fr/insalyon/citi/golo/compiler/ParseTreeToGoloIrVisitor.java, src/main/jjtree/Golo.jjt, src/test/java/fr/insalyon/citi/golo/compiler/CompileAndRunTest.java, src/test/resources/for-execution/loopings.golo, src/test/resources/for-parsing-and-compilation/loops.golo
This introduces support for guards in foreach loops, as in:
```golo
foreach arg in args when arg: length() > 2 {
println("  " + arg)
}
```
This is syntaxic sugar, equivalent to:
```golo
foreach arg in args {
if arg: length() > 2 {
println("  " + arg)
}
}
```
=> [471130] Guarded loops

src/main/java/fr/insalyon/citi/golo/runtime/OperatorSupport.java, src/main/ruby/generate_math.rb, src/test/java/fr/insalyon/citi/golo/compiler/CompileAndRunTest.java, src/test/resources/for-execution/operators.golo, src/test/resources/for-execution/unions.golo
The implementation of comparison operators was done using `compareTo`,
which fails when comparing two numbers of different classes.
The bug is fixed by using `Double.compare` on the two numbers
`doubleValue` when both values are instances of `Number`, falling back
to `compareTo` otherwise.
The same is done for equality, since until now, golo considered
`1 != 1.0`. When the two values are numbers, the double value is
compared by value, `equals` is called otherwise.
Bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=471709
=> [471709] Exception when comparing numbers

src/main/java/fr/insalyon/citi/golo/compiler/utils/StringUnescaping.java, src/main/jjtree/Golo.jjt, src/test/java/fr/insalyon/citi/golo/compiler/CompileAndRunTest.java, src/test/resources/for-execution/returns.golo
- fixes this:
```golo
print("<\\t>")
```
will print:
```
<\    >
```
but the expected value is
```
<\t>
```
- add the ability to the parser to deal with special characters using single quote notation
=> Fix special characters escaping in String and char

src/main/java/fr/insalyon/citi/golo/compiler/ParseTreeToGoloIrVisitor.java, src/test/java/fr/insalyon/citi/golo/compiler/CompileAndRunTest.java
Operators are more naturally left-associative than right-associative.
The previous implementation was right-associative by mistake.
=> [471716] Make the operators left-associative

doc/augmentations.asciidoc, src/main/java/fr/insalyon/citi/golo/runtime/MethodInvocationSupport.java, src/test/resources/for-execution/augmentations-with-fallback.golo
Before, the parameter "name" (name of the function) was "fixed" (you can only call it "name")
augment java.lang.String {
function fallback = |this, name, args...| -> "Fallback for this " + this + " named " + name + " with args" + args: asList()
}
Now, you can name it as you want:
augment java.lang.String {
function fallback = |this, functionName, args...| -> "Fallback for this " + this + " functionName " + name + " with args" + args: asList()
}
=> The function name parameter isn't necessarily called "name"

doc/unions.asciidoc, samples/union.golo, src/main/java/fr/insalyon/citi/golo/compiler/JavaBytecodeUnionGenerator.java, src/main/java/gololang/Unknown.java, src/test/java/fr/insalyon/citi/golo/compiler/CompileAndRunTest.java, src/test/resources/for-execution/unions.golo
A union has now special methods to test its kind (type) as well as the
values of its members if applicable. This make the use of unions in
`match` constructs easier and more readable.
For instance, given the union:
```golo
union Tree = {
Empty
Leaf = { value }
Node = { left, right }
}
```
one can now write a match like:
```golo
function foo = |elt| -> match {
when elt: isEmpty() then "empty"
when elt: isLeaf() then "leaf"
when elt: isNode(Empty(), Empty()) then "node with empty children"
when elt: isNode() then "a node"
}
```
In the same way, a union:
```golo
union Option = {
Some = {value}
None
}
```
can be tested with:
```golo
if v: isNone() {
// ...
}
if v: isSome(null) {
// a some, but containing null (not a good idea)
}
if v: isSome(42) {
// a some containing 42
}
if v: isSome() {
// …
```
=> Adds special methods to unions.

src/main/java/fr/insalyon/citi/golo/compiler/ClosureCaptureGoloIrVisitor.java, src/main/java/fr/insalyon/citi/golo/compiler/JavaBytecodeGenerationGoloIrVisitor.java, src/main/java/fr/insalyon/citi/golo/compiler/LocalReferenceAssignmentAndVerificationVisitor.java, src/main/java/fr/insalyon/citi/golo/compiler/ir/GoloIrVisitor.java, src/main/java/fr/insalyon/citi/golo/compiler/ir/IrTreeDumper.java, src/main/java/fr/insalyon/citi/golo/compiler/ir/NamedArgument.java, src/test/java/fr/insalyon/citi/golo/compiler/CompileAndRunTest.java, src/test/resources/for-execution/namedparameters-function-calls.golo
The implementation of named parameters did not let visitors go through the expression statement.
=> [473133] Error on invocations and named parameters

doc/predefined-functions.asciidoc, src/main/java/gololang/Predefined.java, src/test/java/gololang/PredefinedTest.java
rename `reversed_range` to `reversedRange`, and create a new
*deprecated* `reversed_range` delegating on it.
=> Fix: inconsistent naming for reversed_range

doc/predefined-functions.asciidoc, src/main/java/gololang/Predefined.java
The new predefined `ref` function returns an `AtomicReference` on the
given object. This is just a helper function around
`java.util.concurrent.atomic.AtomicReference`.
Useful whenever an explicit reference is needed, for instance to create
a closure with internal mutable state:
```golo
function counter = |init| {
let current = ref(init)
return -> current: getAndSet(current: get() + 1)
}
function counter = |init, stepFun| {
let current = ref(init)
return -> current: getAndUpdate(stepFun)
}
let c = counter(3)
c() # -> 3
c() # -> 4
c() # -> 5
let c2 = counter(3, |x| -> x * 2)
c() # -> 3
c() # -> 6
c() # -> 12
```
=> Adds a ref predefined function creating reference

src/main/java/gololang/AbstractRange.java, src/main/java/gololang/CharRange.java, src/main/java/gololang/IntRange.java, src/main/java/gololang/LongRange.java
This is generally better to use static vs instance-attached inner classes (performance, GC, etc).
Another point is that this makes the Eclipse compiler happy due to a bug it has.
=> Make the range classes use a static inner class

src/main/jjtree/org/eclipse/golo/compiler/parser/Golo.jjt
The same parsing error appears multiple times.
as example:
```golo
module test
function main = |args| {
let a = "aBc
}
```
prints 3 times the same error:
```
[error] In Golo module: test.golo
[error] Encountered unexpected  <INVALID> `\"`  at line 5, column 11
[error] Encountered unexpected  <INVALID> `\"`  at line 5, column 11
[error] Encountered unexpected  <INVALID> `\"`  at line 5, column 11
```
=> Fix: the same parsing error appears multiple times

doc/augmentations.asciidoc, doc/functions.asciidoc, src/main/java/org/eclipse/golo/compiler/ir/GoloModule.java
Import explicit modules *before* implicit ones (e.g.
`gololang.StandardAugmentations`) such that we can for instance redefine
standard augmentations.
When a type is augmented several times with the same method, the first one is used, that is the one defined in the first imported module.
This is ok, since you can “override” an augmentation by changing the import order. However, since some modules are implicitly imported first (e.g. `StandardAugmentations`), it is not possible to redefine augmentations specified in these modules, i.e. one can’t redefine standard augmentations. 
This limit the usefulness of augmentations. For instance, suppose one want to define a `reduce` method on a specific `struct`. Since a `struct` is a subclass of `GoloStruct`, that implements `Iterable`, and since …
=> Change implicit import order

src/main/java/org/eclipse/golo/compiler/ClosureCaptureGoloIrVisitor.java, src/main/java/org/eclipse/golo/compiler/LocalReferenceAssignmentAndVerificationVisitor.java, src/main/java/org/eclipse/golo/compiler/ParseTreeToGoloIrVisitor.java, src/main/java/org/eclipse/golo/compiler/ir/ClosureReference.java, src/main/java/org/eclipse/golo/compiler/ir/GoloFunction.java, src/test/java/org/eclipse/golo/compiler/CompileAndRunTest.java, src/test/resources/for-execution/module-state-closures.golo
Their was some issues when mixing module state and closure:
- when a local closure used a module state value, it was captured, causing runtime errors
- when a module state containing a closure was defined after a regular functions, the reference tables was merged, causing compilation errors
This PR fixes both issues.
=> Fix: issues when mixing module state and closures

doc/structs.asciidoc, src/main/java/gololang/GoloStruct.java, src/main/java/gololang/Tuple.java, src/test/java/org/eclipse/golo/compiler/CompileAndRunTest.java, src/test/resources/for-execution/structs.golo
`GoloStruct` now implement `Comparable`, by comparing their members
pairwise in lexicographical order. `Tuple::compareTo` is used, doing
`this.values.compareTo(other.values())`
This allow to directly compare structures, using classical operators:
```golo
struct Couple = { x, y }
...
require(Couple(1, 2) < Couple(2, 4), "err")
```
An exception is raised if the structure are different, such that two
different structures with the same members are not comparable, for instance:
```golo
Couple(1, 2) < Point(2, 4)
```
will fail.
=> Make structures comparable

doc/structs.asciidoc, src/main/java/gololang/GoloStruct.java, src/main/java/org/eclipse/golo/runtime/OperatorSupport.java, src/test/java/org/eclipse/golo/compiler/CompileAndRunTest.java
This proposed change invalidates operator call sites on `ClassCastException` rather than through a
branching `guardWithTest` method handle combinator. This removes 2 `instanceof` checks on each
call.
=> Operator call sites with catchException instead of a guardWithTest

doc/augmentations.asciidoc, src/main/java/org/eclipse/golo/cli/command/GoloGoloCommand.java, src/main/java/org/eclipse/golo/runtime/AugmentationMethodFinder.java, src/test/java/org/eclipse/golo/internal/testing/TestUtils.java, src/test/java/org/eclipse/golo/runtime/AugmentationResolutionTest.java, src/test/resources/for-execution/call-resolution/call-stack-lookup.golo, src/test/resources/for-execution/call-resolution/data.golo, src/test/resources/for-execution/call-resolution/lib.golo
When an augmentation is defined, it is only visible if the module using
it has imported the module defining it. This limits the ability to
create generic functions using any augmented object.
The solution is to look up in the call stack if a complying augmentation
had been imported in the calling module.
=> FIX #320: Lookup augmentations in call stack

src/main/golo/ansicodes.golo, src/test/java/gololang/AnsiCodesTest.java, src/test/resources/for-test/ansicodes.golo
Replace `println` by `print` to not jump to the new line when the cursor is moved.
=> Fix cursor movement

src/main/java/org/eclipse/golo/runtime/ArrayMethodFinder.java, src/main/java/org/eclipse/golo/runtime/AugmentationMethodFinder.java, src/main/java/org/eclipse/golo/runtime/MethodFinder.java, src/main/java/org/eclipse/golo/runtime/MethodInvocation.java, src/main/java/org/eclipse/golo/runtime/MethodInvocationSupport.java, src/main/java/org/eclipse/golo/runtime/RegularMethodFinder.java, src/test/java/org/eclipse/golo/compiler/CompileAndRunTest.java, src/test/java/org/eclipse/golo/compiler/testing/support/ClassWithOverloadedMethods.java, src/test/java/org/eclipse/golo/runtime/RegularMethodFinderTest.java, src/test/resources/for-execution/java-overloaded-methods.golo
This supports resolving and invalidating Java overloaded instance methods.
=> Support Java overloaded instance methods

src/main/java/org/eclipse/golo/compiler/JavaBytecodeGenerationGoloIrVisitor.java, src/main/java/org/eclipse/golo/compiler/ir/ReferenceTable.java, src/main/java/org/eclipse/golo/runtime/OperatorSupport.java, src/test/java/org/eclipse/golo/compiler/CompileAndRunTest.java, src/test/java/org/eclipse/golo/runtime/OperatorSupportTest.java, src/test/resources/for-execution/operators.golo
FIX #342
Replace the call to an invoke dynamic method by a generated bytecode
whose evaluation is lazy. For instance, in:
```golo
"plop" orIfNull getPlop()
```
the `getPlop` function is not called anymore.
=> Make the orIfNull operator lazy

src/main/java/org/eclipse/golo/compiler/ParseTreeToGoloIrVisitor.java, src/main/java/org/eclipse/golo/compiler/ir/GoloModule.java, src/main/java/org/eclipse/golo/compiler/ir/Struct.java, src/main/java/org/eclipse/golo/compiler/ir/Union.java, src/test/java/org/eclipse/golo/compiler/CompilerTest.java, src/test/resources/for-test/duplicated-struct.golo, src/test/resources/for-test/duplicated-type.golo, src/test/resources/for-test/duplicated-union-value.golo, src/test/resources/for-test/duplicated-union.golo
When two types (`struct` or `union`) with the same name were declared in
the same module, the code compiled without error, but an obscure
exception was raised at runtime
The case is now checked when building the IR, so that we have a clear
compiling error.
This fix the #323 issue.
=> FIX #323: Check for duplicated types compile time

src/main/golo/async.golo, src/main/golo/json.golo, src/main/golo/lazylists.golo, src/main/java/org/eclipse/golo/compiler/ParseTreeToGoloIrVisitor.java, src/main/java/org/eclipse/golo/compiler/ir/IrTreeDumper.java, src/test/java/org/eclipse/golo/compiler/CompileAndRunTest.java, src/test/resources/for-execution/call-resolution/mixin-test.golo, src/test/resources/for-execution/comprehension.golo, src/test/resources/for-execution/destruct.golo, src/test/resources/for-execution/direct-anon-call.golo, src/test/resources/for-execution/module-state-closures.golo, src/test/resources/for-execution/namedarguments-anoncall.golo, src/test/resources/for-execution/operators.golo, src/test/resources/for-execution/structs.golo, src/test/resources/for-execution/unions.golo, src/test/resources/for-parsing-and-compilation/decorators.golo, src/test/resources/for-parsing-and-compilation/doc.golo, src/test/resources/for-parsing-and-compilation/unions.golo
There is a issue when doing anonymous calls, i.e. calls directly applied
on references, on lambda, on partialized functions, or on functions
returned by other functions, when using named arguments.
The issue is due to an incorrect flagging in the AST to IR conversion:
the anonymous function invocations were not flagged as using named
arguments. Therefore, the magic behind did not happened, which caused
the arguments not being stacked, and thus a weired runtime error.
(Also some space cleaning)
=> FIX #335: Named arguments and anonymous calls

doc/java-interop.asciidoc, src/main/java/org/eclipse/golo/runtime/MethodInvocationSupport.java, src/main/java/org/eclipse/golo/runtime/PropertyMethodFinder.java, src/main/java/org/eclipse/golo/runtime/RegularMethodFinder.java, src/main/java/org/eclipse/golo/runtime/TypeMatching.java, src/test/java/org/eclipse/golo/runtime/MethodInvocationSupportTest.java
This PR adds a property support to Golo. If `the RegularMethodFinder` can't do
the resolution, then the `PropertyMethodFinder` will seek for an accessor or
mutator after ensuring the method name matches to a field name.
Related issue: #198 
* Is the fluent aspect a good thing? Is it to the language or to the dev to make the getter/setter fluent?
=> Property-style method support

src/main/java/gololang/error/Result.java, src/test/resources/for-test/result.golo
The mapping function was not used, the recover one was used in both cases
(note to future me: don't use 42 in every test case)
=> Fix a bug in Result::either

doc/basics.asciidoc, src/main/java/org/eclipse/golo/cli/command/CompilerCommand.java, src/main/java/org/eclipse/golo/compiler/GoloCompiler.java
The golo compile used to work with an optional --output parameter to
specify a target directory.
With this change, if the target ends with '.jar', then the compilation
results are assembled to a Jar archive instead.
=> Compile to Jar archives

src/main/java/gololang/Predefined.java, src/main/java/org/eclipse/golo/runtime/Extractors.java, src/main/java/org/eclipse/golo/runtime/Loader.java, src/main/java/org/eclipse/golo/runtime/TypeMatching.java, src/test/java/gololang/PredefinedTest.java, src/test/java/org/eclipse/golo/compiler/CompileAndRunTest.java, src/test/resources/for-execution/closures.golo
- small refactor of `Predefined::fun`:
just use existing methods from `Extractors` and `TypeMatching`;
- add a `varargs` parameter to `fun` to specify if a variable arity
method is required or not;
- search in modules imported by the one we are looking in if no function
is found (use the first function found).
=> FIX #249: use imported modules in fun

doc/closures.asciidoc, src/main/java/org/eclipse/golo/compiler/SugarExpansionVisitor.java, src/main/java/org/eclipse/golo/compiler/ir/Builders.java, src/main/jjtree/org/eclipse/golo/compiler/parser/Golo.jjt, src/test/java/org/eclipse/golo/compiler/CompileAndRunTest.java, src/test/resources/for-execution/closures.golo, src/test/resources/for-parsing-and-compilation/closures.golo
Introduces a extended notation for function reference literals that
allows to specify the arity of the function.
The general syntax is `^package.module.::function\arity`
Example:
```golo
function foo = |a, b| -> a * b
function foo = |x| -> x + 1
function call_foo = {
return ^foo\2(^foo\1(20), 2)
}
```
=> New syntax to specify arity in function literals

doc/basics.asciidoc, src/main/golo/functions.golo, src/main/golo/standard-augmentations.golo, src/main/java/gololang/FunctionReference.java, src/main/java/gololang/GoloStruct.java, src/main/java/gololang/Tuple.java, src/main/java/gololang/Union.java, src/main/java/org/eclipse/golo/compiler/JavaBytecodeUnionGenerator.java, src/main/java/org/eclipse/golo/runtime/ArrayMethodFinder.java, src/test/java/gololang/OperatorsAndHofTest.java, src/test/resources/for-execution/destruct.golo, src/test/resources/for-test/functions.golo
Adds a module containing useful functions to create
or change functions, to use in HOF for example.
Mainly operators as curried functions, composition functions, arity changing functions.
Adds a `toArray` and a `destruct` method to tuples, arrays, unions and structs to ease
polymorphism:
Adds tooling method to `FunctionReference`:
an `arity` function, and `invokeOrBind`: a function that apply arguments, binding them or
invoking the function according to the number.
=> Functions and operators utilities

doc/basics.asciidoc, src/main/java/org/eclipse/golo/compiler/JavaBytecodeGenerationGoloIrVisitor.java, src/main/java/org/eclipse/golo/runtime/OperatorSupport.java, src/main/jjtree/org/eclipse/golo/compiler/parser/Golo.jjt, src/main/ruby/generate_math.rb, src/test/java/org/eclipse/golo/compiler/CompileAndRunTest.java, src/test/resources/for-execution/arrays.golo, src/test/resources/for-execution/operators.golo, src/test/resources/for-parsing-and-compilation/simple-returns.golo
Fix #374 by:
* allowing `_` in floating numbers and negative exponent in scientific notation;
* adding literal notation for `BigInteger` and `BigDecimal` using the `_B` suffix;
* extending operators to deal with `BigInteger` and `BigDecimal` values.
=> Extended literal notation for floating numbers

doc/basics.adoc, share/shell-completion/golo-bash-completion, src/main/java/org/eclipse/golo/cli/command/CheckCommand.java, src/main/java/org/eclipse/golo/cli/command/spi/CliCommand.java, src/main/resources/META-INF/services/org.eclipse.golo.cli.command.spi.CliCommand
Adds a `check` command to the `golo` binary. This command does the same
tasks as the `compile` command, namely parse input files and run the
compile time IR verifications, but does not produce result files.
This command can be useful to integrate golo with editor plugins such as
Vim Syntastic.
FIX #324
=> Check command

src/main/java/org/eclipse/golo/cli/command/CheckCommand.java, src/main/java/org/eclipse/golo/compiler/GoloCompiler.java
When processing several files, and without the `--exit` option, only the
first error was displayed, for every file with an error, because the
exception builder was not reset between files.
Also adds a verbose option to display the checked file name.
=> FIX: bug when checking several files

build.gradle, doc/basics.adoc, src/main/java/org/eclipse/golo/cli/Main.java, src/main/java/org/eclipse/golo/cli/command/CompilerCommand.java, src/main/java/org/eclipse/golo/cli/command/DiagnoseCommand.java, src/main/java/org/eclipse/golo/cli/command/GoloGoloCommand.java, src/main/java/org/eclipse/golo/cli/command/ShebangCommand.java, src/main/resources/META-INF/services/org.eclipse.golo.cli.command.spi.CliCommand
ref: [shebang](https://en.wikipedia.org/wiki/Shebang_(Unix))
This feature aim to run golo application as simple runnable script.
```
golo shebang /path/to/script.golo arg1 arg2
```
this command do:
- compile every golo files in the `/path/to/` directory recursively
- add every `jar` files in the `/path/to/` directory recursively to the current classpath
- run `script.golo` main funtion with `/path/to/script.golo`, `args1` and `arg2` as parameters
so we can now shebang this script file (script.golo):
```golo
#!/path/to/golo  shebang
module script
function main = |args| {
foreach arg in args {
println(arg)
}
}
```
then in a shell `./script.golo arg1 arg2` will print
```
./script.golo
arg1
arg2
```
=> Run Golo application from a shebanged script

src/main/java/org/eclipse/golo/compiler/ir/ReferenceTable.java, src/test/resources/for-execution/destruct.golo
Relinking reference tables for a block inside a block
may cause dublicate reference declaration.
This fixes #391
=> Fix destructuring assignment inside a closure

src/main/jjtree/org/eclipse/golo/compiler/parser/Golo.jjt
Fix a bug introduced in https://github.com/eclipse/golo-lang/commit/2f1dc71787506edd45fa1d1242684cfbbb03b940 and identified by @vvdleun in #407 
When declaring a name with `let` or `var` but affecting no value, the parser hangs.
The issue was a lookahead to high for this expression, added for destructuring.
=> FIX: #407 Compiler hangs on unassigned variable

src/main/golo/functions.golo, src/test/resources/for-test/functions.golo
The current implementation of `gololang.Functions::io` ignore the value
returned by the wrapped function.
It now returns its argument if the wrapped function returned `null`, but
it return the result otherwise. This allows to wrap IO *reading*
functions, which was not previously possible.
=> Allow “input” in the `io` HOF

src/main/java/org/eclipse/golo/doc/AbstractProcessor.java, src/main/java/org/eclipse/golo/doc/HtmlProcessor.java, src/main/resources/org/eclipse/golo/doc/src-html, src/main/resources/org/eclipse/golo/doc/template-html
This implements the first point in #383: the golodoc now links to a html version of the source file, to the line where the documented element is.
=> Link golodoc and source file

.gitignore, README.md, build.gradle, gradle/wrapper/gradle-wrapper.properties
This makes it easier to locate these files from an IDE.
=> Move the JavaCC/JJTree generated code to src/main/generated

build.gradle
When I try to compile the Golo project on an OS that does use UTF-8 as default encoding some warnings are displayed beacause of some UTF-8 chars present in Java comments and javadoc.
This one fixes this issue.
=> Add compiler option to set UTF-8 as default encoding

src/test/java/org/eclipse/golo/compiler/CompileAndRunTest.java, src/test/resources/for-execution/classes.golo
TL;DR: the case unsensitive filesystems sucks :wink:.
Class resolution requires classpath walking, especially from imports resolution.
If a class is not found, then a `ClassNotFoundException` should be thrown.
for example the following test should throw a `ClassNotFoundException`:
```golo
function unknown_class = -> unknown.class
```
but , in some cases, it's a `NoClassDefFoundError` that is thrown.
This is because:
- the `gololang.Unknown` class exists
- the `Unknown.class` file is in the filesystem (not in a jar file)
- the filesystem is not case sensitive
- Jacoco use `loader.getResourceAsStream("gololang/unknown.class")` to get the bytecode to instrument
- `loader.getResourceAsStream("gololang/unknown.class")` return the content of the `"gololang/Unknown.class"` file in this case
- …
=> Fix fragile test on a not case sensitive FS

doc/java-interop.adoc, src/main/java/org/eclipse/golo/runtime/AugmentationMethodFinder.java, src/main/java/org/eclipse/golo/runtime/ClosureCallSupport.java, src/main/java/org/eclipse/golo/runtime/FunctionCallSupport.java, src/main/java/org/eclipse/golo/runtime/MethodFinder.java, src/main/java/org/eclipse/golo/runtime/MethodInvocation.java, src/main/java/org/eclipse/golo/runtime/NamedArgumentsHelper.java, src/main/java/org/eclipse/golo/runtime/PropertyMethodFinder.java, src/main/java/org/eclipse/golo/runtime/RegularMethodFinder.java, src/main/java/org/eclipse/golo/runtime/TypeMatching.java, src/main/java/org/eclipse/golo/runtime/Warnings.java, src/test/resources/for-execution/namedarguments-anoncall.golo, src/test/resources/for-execution/namedparameters-function-calls.golo
partial fix for issues raised in #351 and #352 comments.
- deal with the receiver in method calls: the receiver argument has no
name; moreover, for regular methods, the receiver parameter has no name
(but is present in the signature)
- display a warning if calling a function without parameter names with
named arguments. It can be disabled via properties.
=> Refactor reordering of named parameters

src/main/java/org/eclipse/golo/compiler/ir/GoloFunction.java, src/main/java/org/eclipse/golo/compiler/ir/IrTreeDumper.java, src/test/java/org/eclipse/golo/compiler/CompileAndRunTest.java, src/test/resources/for-execution/closures.golo
When a closure references itself elsewhere than in a recursive call,
an `Uninitialized reference` error is raised. For instance, in
```golo
function test = {
let fun = |x| -> match {
when x is null then fun
otherwise x
}
return fun(null)
}
```
the null case fails. In the generated function `__$$_sugar_closure_X`,
an assignment to `fun` of the closure reference is injected, but it was
mistakenly not defined as a declaring one, which fool the
`LocalReferenceAssignmentAndVerificationVisitor` in thinking the
reference is not initialized.
=> Fix a bug on self reference in closures

doc/functions.adoc, src/main/java/org/eclipse/golo/compiler/ir/GoloModule.java, src/main/java/org/eclipse/golo/runtime/ClassReferenceSupport.java, src/main/java/org/eclipse/golo/runtime/FunctionCallSupport.java, src/main/java/org/eclipse/golo/runtime/Warnings.java, src/test/resources/for-execution/imports-metadata.golo
FIX #439
When failing to load a class, either in a class reference or in a
function resolution (via imported modules or FQN call), a warning is
printed. This ease the debugging of typo or classpath errors.
The warning can be disabled by the `golo.warnings.unavailable-class`
system property.
=> Print a warning when unable to load a class

src/main/golo/errors.golo, src/test/resources/for-test/result.golo
This HOF create a function that can execute a block and apply a given
function if an exception occurs. It can be used as a decorator.
=> Adds a `catcher` HOF in gololang.Errors

doc/functions.adoc, src/main/java/org/eclipse/golo/runtime/Warnings.java
In #440, a warning was added when a module can't be loaded.
The feature works well when importing Golo modules or Java classes in
order to use static functions (e.g. `import java.util.Collections`)
However, many false positives are reported. For instance, it is common
practice to import a Java package in Golo code, to use provided classes,
similar to Java `import foo.*;` or to keep a namespace for static
methods, e.g.
```golo
import java.util
import java.nio.file
Collections.singleton(Paths.get(...))
```
instead of
```golo
import java.util.Collections
import java.nio.file.Paths
singleton(get(...))
```
While the in the case of `Collections`, static methods can be imported
in the module scope, it's more readable to keep `get` prefixed.
In the first case, the resolution for `Paths.get` is …
=> Turn warning on unfound import off by default

src/main/java/org/eclipse/golo/compiler/PackageAndClass.java, src/main/java/org/eclipse/golo/compiler/ir/GoloModule.java, src/test/java/org/eclipse/golo/compiler/CompileAndRunTest.java
In a module `foo.bar.Baz`, we add an implicit `import foo.bar`, such
that modules in the same package are directly visible.
This mimic the Java behavior in which classes in the same package are
directly visible without importing them.
For instance, given
module foo.bar.Plop
function daPlop = -> "Plop"
the module `foo.bar.Baz` can directly call `Plop.daPlop()`.
=> Implicit import of the current package

src/main/java/org/eclipse/golo/compiler/LocalReferenceAssignmentAndVerificationVisitor.java
As discussed in the #380 issue thread, the expected behavior is not that
clear. The current one mimic the java one, it is indeed a realy bad idea
to redefine/shadow an existing variable in a more local scope.
This fix just display the correct error message that we are redefining a
variable.
=> Fix #380 on variable scope

src/main/java/gololang/GoloStruct.java, src/main/java/org/eclipse/golo/compiler/JavaBytecodeStructGenerator.java, src/main/resources/messages.properties, src/main/resources/messages_fr_FR.properties
Misc improvements of the struct generated classes:
- make `toArray` abstract and generated instead of using `values`; make `values` use `toArray` instead of being generated,
- l10n of runtime exceptions (trying to access a private field, etc.)
- make returned type of setters and copy the struct itself instead of `GoloStruct`
=> Struct improvement

doc/functions.adoc, src/main/java/org/eclipse/golo/compiler/ParseTreeToGoloIrVisitor.java, src/main/java/org/eclipse/golo/compiler/parser/ASTImportDeclaration.java, src/main/jjtree/org/eclipse/golo/compiler/parser/Golo.jjt, src/test/java/org/eclipse/golo/compiler/CompileAndRunTest.java, src/test/resources/for-execution/imports-metadata.golo
FIX #322
A module can be imported without specifying its fully qualified name in
a module of *the same package or sub-package* by prefixing its name with a `.`
For instance
```golo
module a.b.C
import .d.E
import .F
```
is the same as
```golo
module a.b.C
import a.b.d.E
import a.b.F
```
=> Relative import

doc/functions.adoc, src/main/java/org/eclipse/golo/compiler/ParseTreeToGoloIrVisitor.java, src/main/java/org/eclipse/golo/compiler/ir/GoloModule.java, src/main/java/org/eclipse/golo/compiler/parser/ASTImportDeclaration.java, src/main/jjtree/org/eclipse/golo/compiler/parser/Golo.jjt, src/test/java/org/eclipse/golo/compiler/CompileAndRunTest.java, src/test/resources/for-execution/imports-metadata.golo
Allows to import several modules from the same package at once.
For instance:
```golo
import foo.{
bar.Baz,
Plop
}
```
is equivalent to
```golo
import foo.bar.Baz
import foo.Plop
```
=> Multiple imports

src/main/java/org/eclipse/golo/cli/command/spi/CliCommand.java
When introducing l10n and colors, I changed the way throwables are
printed at the top level. However, this change prevented some errors to
be visible. This PR changes the default to print the error.
=> Fix error printing in CLI

src/main/java/org/eclipse/golo/cli/command/DocCommand.java, src/main/java/org/eclipse/golo/compiler/GoloCompiler.java, src/main/java/org/eclipse/golo/compiler/ParseTreeToGoloIrVisitor.java, src/main/java/org/eclipse/golo/compiler/ir/AbstractGoloIrVisitor.java, src/main/java/org/eclipse/golo/doc/AbstractProcessor.java, src/main/java/org/eclipse/golo/doc/AugmentationDocumentation.java, src/main/java/org/eclipse/golo/doc/CtagsProcessor.java, src/main/java/org/eclipse/golo/doc/FunctionDocumentation.java, src/main/java/org/eclipse/golo/doc/HtmlProcessor.java, src/main/java/org/eclipse/golo/doc/MarkdownProcessor.java, src/main/java/org/eclipse/golo/doc/ModuleDocumentation.java, src/test/java/org/eclipse/golo/doc/DocumentationRenderingTest.java, src/test/java/org/eclipse/golo/doc/ModuleDocumentationTest.java
In the prevision of introducing macros, the golodoc should be generated from the IR instead of the AST, since macros can inject new public types and functions in a module that should be documented.
This refactor also loosen the coupling between the AST and the rest of the code base, being even less dependent on the parser.
=> Generate doc from IR instead of AST

src/main/java/org/eclipse/golo/cli/command/InitCommand.java
To improve the `golo new` command, project type initializers were
introduced. However, they were stored in a static map, and used golo
template for the files to generate. Therefore, a template compilation
was triggered for every golo run, even when an other command was used.
The initializer are made lazy to prevent this behavior.
=> Lazy project type initialization

README.md
The current Gitter badge URL contains a space, which makes the
badge incorrectly display as a link (at least in GitHub's rendering).
Changing the space for '%20' fixes this.
Change preview:
=> Fix Gitter badge URL by encoding the space

src/main/java/gololang/Predefined.java, src/main/java/org/eclipse/golo/runtime/FunctionCallSupport.java, src/main/java/org/eclipse/golo/runtime/WithCaller.java, src/test/java/gololang/PredefinedTest.java
This fix #319 by injecting the caller class in the function call
and testing for equality.
The injection mechanism is somewhat a hack, but I could not find a
better solution. Moreover, maybe it could be reused elsewhere, since
it's quite generic.
=> FIX #319: `fun` allows access to private functions.

src/main/java/org/eclipse/golo/runtime/MethodInvocationSupport.java, src/test/java/org/eclipse/golo/runtime/MethodInvocationSupportTest.java
As described in #471, the priority magic is used only if no regular
method exists.
=> FIX #471: property method priority

src/main/java/org/eclipse/golo/doc/AbstractProcessor.java, src/main/java/org/eclipse/golo/doc/ModuleDocumentation.java
When no documentation was provided for an augmentation, "null" was
displayed.
=> FIX: bug in documentation generation

src/main/jjtree/org/eclipse/golo/compiler/parser/Golo.jjt, src/test/java/org/eclipse/golo/compiler/CompileAndRunTest.java, src/test/resources/for-execution/returns.golo
Add the ability to put some comments between
the `return` keyword and the returned statment.
=> Fix the 509 issue

src/main/java/gololang/FunctionReference.java, src/main/java/gololang/Predefined.java, src/test/java/gololang/FunctionReferenceTest.java, src/test/resources/for-execution/augmentations-with-fallback.golo
When composing a variadic function, the collector status is lost, thus
the resulting function can't be used as varargs.
For instance:
```golo
let f = (|a...| -> a: toString()): andThen(|a| -> a)
f("a", "b")
f: invoke("a", "b")
```
Both calls fail with a `WrongMethodTypeException`. A solution is to add
a `: asVarargsCollector()` call, but it is counter intuitive: the
composed function should directly accept the same arguments as the first
function and return the same type as the second one.
This is fixed by converting the composed function into a varargs
collector if the original one was.
The same issue occurred when binding parameters on varargs functions.
A last bug fixed here occurred when composing java functions whose types
do not match exactly even if compatible
(e.g. composing `A -> …
=> Fix a bug in function composition

src/main/java/org/eclipse/golo/runtime/Extractors.java, src/main/java/org/eclipse/golo/runtime/FunctionCallSupport.java, src/main/java/org/eclipse/golo/runtime/TypeMatching.java, src/test/java/org/eclipse/golo/runtime/PrimitiveOverloadingTest.java, src/test/java/org/eclipse/golo/runtime/TypeMatchingTest.java, src/test/resources/for-execution/primitive-overloading.golo
When java method expect e.g. a float and it is called with a int, the
method is not found (since the big method resolution refactoring).
- adds a substituability comparison for method params
- use Extractors in function call resolution
=> FIX #513: issue with implicit upcast of primitive

src/main/java/org/eclipse/golo/compiler/ParseTreeToGoloIrVisitor.java, src/main/java/org/eclipse/golo/compiler/ir/BinaryOperation.java
Previously, golo code such as
```golo
a: f(): g(): h()
```
created an IR like
```
Binary operator: :
Reference lookup: a
Binary operator: :
Method invocation: f, null safe? -> false
Binary operator: :
Method invocation: g, null safe? -> false
Method invocation: h, null safe? -> false
```
The IR is now
```
Binary operator: :
Binary operator: :
Binary operator: :
Reference lookup: a
Method invocation: f, null safe? -> false
Method invocation: g, null safe? -> false
Method invocation: h, null safe? -> false
```
which is equivalent to 
```golo
((a: f()): g()): h()
```
=> Make method invocation left associative

src/main/java/org/eclipse/golo/runtime/FunctionCallSupport.java, src/test/java/org/eclipse/golo/runtime/FunctionCallSupportTest.java, src/test/java/org/eclipse/golo/runtime/ImportedFunctionResolutionTest.java, src/test/resources/for-execution/call-resolution/bar.golo, src/test/resources/for-execution/call-resolution/foo.golo, src/test/resources/for-execution/call-resolution/plop.golo, src/test/resources/for-execution/call-resolution/v0.golo, src/test/resources/for-execution/call-resolution/v1.golo, src/test/resources/for-execution/call-resolution/v1b.golo, src/test/resources/for-execution/call-resolution/v2.golo, src/test/resources/for-execution/call-resolution/v2b.golo, src/test/resources/for-execution/call-resolution/v2c.golo, src/test/resources/for-execution/call-resolution/v2inv.golo, src/test/resources/for-execution/call-resolution/v3-1-1.golo, src/test/resources/for-execution/call-resolution/v3-1-2.golo, src/test/resources/for-execution/call-resolution/v3-1-3.golo, src/test/resources/for-execution/call-resolution/v3-2-1.golo, src/test/resources/for-execution/call-resolution/v3-2-2.golo, src/test/resources/for-execution/call-resolution/v3-3.golo, src/test/resources/for-execution/call-resolution/v4.golo, src/test/resources/for-execution/dynamic-evaluation.golo
Fix #340 
The issue was in the way the imported namespace was merged with the
specified function name, in particular when the called name was relative
to an imported namespace.
Added debug infos in function call resolution.
=> FIX 340: Issues with imported functions resolution

src/main/java/org/eclipse/golo/doc/AbstractProcessor.java, src/main/java/org/eclipse/golo/doc/HtmlProcessor.java
Relative URIs in the doc under windows had backslash as separators.
=> Fix bug with Windows relative URIs in doc

doc/decorators.adoc, doc/functions.adoc, src/main/java/gololang/ir/FunctionInvocation.java, src/main/java/gololang/ir/GoloFunction.java, src/main/java/gololang/ir/IrTreeDumper.java, src/main/java/org/eclipse/golo/compiler/ClosureCaptureGoloIrVisitor.java, src/main/java/org/eclipse/golo/compiler/JavaBytecodeGenerationGoloIrVisitor.java, src/main/java/org/eclipse/golo/compiler/JavaBytecodeUtils.java, src/main/java/org/eclipse/golo/compiler/ParseTreeToGoloIrVisitor.java, src/main/java/org/eclipse/golo/compiler/SugarExpansionVisitor.java, src/main/java/org/eclipse/golo/runtime/AugmentationMethodFinder.java, src/main/java/org/eclipse/golo/runtime/ClosureCallSupport.java, src/main/java/org/eclipse/golo/runtime/FunctionCallSupport.java, src/main/java/org/eclipse/golo/runtime/MethodFinder.java, src/main/java/org/eclipse/golo/runtime/NamedArgumentsHelper.java, src/test/java/org/eclipse/golo/compiler/TceTest.java, src/test/resources/for-execution/comprehension.golo, src/test/resources/for-parsing-and-compilation/tce.golo, src/test/resources/for-test/local-declaration.golo
This is just a small experiment on tail call elimination (#388). This is preliminary work here for feed back.
Since we just identify tail call recursion with a `ReturnStatement` whose expression is a `FunctionCall` to the same function it pertains to, a lot of effectively TC constructions are not covered. For instance, none of the following functions will be optimized, despite being effectively tail recursive:
```golo
function foo = |acc, i| {
if i <= 0 {
return acc
}
let res = foo(acc + 1, i - 1)
return res
}
```
The next step (the hard one) is to try to identify such cases and rewrite the IR to allow the optimization. I fear a lot of special cases that would lead to ugly code.
The other option would be to let the developer properly code the function, but this forbid interesting …
=> Experiment on TCE

src/main/java/gololang/DynamicObject.java, src/main/java/org/eclipse/golo/runtime/MethodInvocationSupport.java, src/test/java/gololang/DynamicObjectTest.java, src/test/java/org/eclipse/golo/compiler/CompileAndRunTest.java, src/test/resources/for-execution/dynamic-objects.golo
I found two bugs in the frozen `DynamicObject` behavior:
- the state was not checked in `undefine`, so one could undefine a property on a frozen object
- the `isFrozen` returned `null`, because is was not considered a reserved method name
=> Fix bugs on frozen DynamicObject

src/main/java/gololang/FunctionReference.java, src/test/resources/for-test/functions.golo
Bug in dealing with variadic functions that can accept more arguments than the number of formal parameters
=> FIX: bug in FunctionReference::acceptArity

doc/documenting.adoc, src/main/golo/gololang/ir.golo, src/main/java/gololang/ir/Struct.java, src/main/java/gololang/ir/TypeWithMembers.java, src/main/java/gololang/ir/Visitors.java, src/main/java/org/eclipse/golo/cli/command/DocCommand.java, src/main/java/org/eclipse/golo/compiler/GoloCompiler.java, src/main/java/org/eclipse/golo/doc/AbstractProcessor.java, src/main/java/org/eclipse/golo/doc/CtagsProcessor.java, src/main/java/org/eclipse/golo/doc/DocumentationElement.java, src/main/java/org/eclipse/golo/doc/HtmlProcessor.java, src/main/java/org/eclipse/golo/doc/MarkdownProcessor.java, src/main/java/org/eclipse/golo/doc/ModuleDocumentation.java, src/main/java/org/eclipse/golo/runtime/AugmentationMethodFinder.java, src/main/java/org/eclipse/golo/runtime/ClosureCallSupport.java, src/main/java/org/eclipse/golo/runtime/FunctionCallSupport.java, src/main/java/org/eclipse/golo/runtime/MethodFinder.java, src/main/java/org/eclipse/golo/runtime/Warnings.java, src/main/resources/messages.properties, src/main/resources/messages_fr_FR.properties, src/main/resources/org/eclipse/golo/doc/package-html, src/main/resources/org/eclipse/golo/doc/template-html, src/test/java/org/eclipse/golo/doc/DocumentationRenderingTest.java, src/test/resources/for-parsing-and-compilation/docpackage/MyModule.golo, src/test/resources/for-parsing-and-compilation/docpackage/README.md
Adds package wide documentation (like `package-info.java`) by using
empty modules (no class generated, only doc) or `README.md` in the same
directory. The package doc links to all modules in the same package.
Such a doc is generated even if no info is provided, only listing
contained modules.
Even when the module is not empty, if modules exists in a "subnamespace"
(e.g. `my.module` and `my.module.sub`), the upper module links to the
others.
Moreover, a description of the module (from the first sentence of the
module golodoc) is included in the index.
=> Package index documentation

doc/basics.adoc
Fixes small typo in line 425, section 1.14 (Collection literals).
=> Fixes typo in basics.adoc

src/main/golo/gololang/ir/DSL.golo, src/main/java/gololang/ir/package-info.java
The `gololang.ir` module containing fluent factory methods for IR nodes
and augmentations on said nodes is renamed `gololang.ir.DSL`.
Indeed, the IR nodes being in the `gololang.ir` java package, a
golo code that `import gololang.ir` had access to the IR nodes and the
fluent API, which was quite elegant.
Since the golo code is compiled after the java code, no conflict was
raised as long as we stayed inside the compiler itself for java code, or
in golo code.
However, trying to use classes from `gololang.ir` package inside 3rd
party java code raise an error since the `gololang.ir` class existed due
to the golo module.
The renaming fixes this aspect, requiring to explicitly import
`gololang.ir.DSL` in order to use the fluent API in golo code.
=> FIX: conflict between golo module and java package
