eclipse/golo-lang

- doc/closures.asciidoc
- doc/predefined-functions.asciidoc
- src/main/java/gololang/Predefined.java
Somehow I forgot to include a documentation along with the development of the feature.
Shame on me.
> Missing documentation for functional interfaces interop

- doc/adapters.asciidoc
- src/main/golo/adapters.golo
- src/test/java/fr/insalyon/citi/golo/compiler/CompileAndRunTest.java
- src/test/resources/for-execution/adapters-helper.golo
A kind of DSL with same notation as DynamicObjects
> Adapters: Proposal for something easier to use than maps 

- src/main/java/fr/insalyon/citi/golo/cli/command/DiagnoseCommand.java
- src/main/java/fr/insalyon/citi/golo/cli/command/DocCommand.java
Cli commands with this issue
- golo diagnose
- golo doc
linked to #266 issue
> fix the package visibility issue on cli commands with validator

- doc/basics.asciidoc
- src/main/golo/standard-augmentations.golo
- src/main/java/fr/insalyon/citi/golo/compiler/GoloCompilationException.java
- src/main/java/fr/insalyon/citi/golo/compiler/ParseTreeToGoloIrVisitor.java
- src/main/java/fr/insalyon/citi/golo/compiler/ir/LoopStatement.java
- src/main/java/fr/insalyon/citi/golo/compiler/parser/ASTCollectionLiteral.java
- src/main/jjtree/Golo.jjt
- src/test/java/fr/insalyon/citi/golo/compiler/CompileAndRunTest.java
- src/test/resources/for-execution/comprehension.golo
Several constructions are allowed:
```golo
list[ x * 2 for x in aList ]
set[ a + b for a, b in aTupleList]
[ a + b for a in [1..6] for b in [1..6] ]
map[ [k, v] for k, v in aMap: entrySet() ]
```
This is not finished yet, needs more polishing (and doc...)
Comments ?
> Collection Comprehension

- doc/basics.asciidoc
- samples/collectionComprehension.golo
Adds a sample file for collections comprehension, and improve the
documentation by adding a comparison with SQL and fixing typos.
> Comprehension sample code and documentation

- src/main/java/org/eclipse/golo/compiler/parser/ParseException.java
> Specialize the ParseException class

- doc/misc.asciidoc
- src/main/golo/ansicodes.golo
> Console ANSI codes support

- doc/misc.asciidoc
> Fix minor typo

- build.gradle
- doc/misc.asciidoc
- src/main/golo/errors.golo
- src/main/java/gololang/error/Result.java
- src/test/java/gololang/error/ResultTest.java
- src/test/resources/for-test/option.golo
- src/test/resources/for-test/result.golo
This introduce some objects, augmentations and functions to deal with
errors (null, exceptions, ...) functional style.
- `Result` type similar to Haskell `Either` or Rust `Result`
- augmentation on java `Optional`
- decorators to adapt function to return or deal with arguments of these
types
Signed-off-by: Yannick Loiseau <yannick.loiseau@univ-bpclermont.fr>
> Add a new library do deal with errors

- build.gradle
Related to https://github.com/cbeust/testng/issues/916
> Upgrade TestNG to 6.9.10

- build.gradle
- src/main/resources/new-project/gradle/build.gradle
- src/main/resources/new-project/maven/pom.xml
Process the Gradle and Maven templates to have the Golo version edited.
> Fix for #367

- .gitignore
- src/main/golo/adapters.golo
- src/main/golo/ansicodes.golo
- src/main/golo/async.golo
- src/main/golo/decorators.golo
- src/main/golo/functions.golo
- src/main/golo/lazylists.golo
- src/main/golo/standard-augmentations.golo
- src/main/java/org/eclipse/golo/doc/AbstractProcessor.java
- src/main/java/org/eclipse/golo/doc/HtmlProcessor.java
- src/main/resources/org/eclipse/golo/doc/index-html
- src/main/resources/org/eclipse/golo/doc/template-html
- src/main/resources/org/eclipse/golo/doc/template-markdown
- src/test/java/org/eclipse/golo/doc/DocumentationRenderingTest.java
- src/test/java/org/eclipse/golo/doc/ModuleDocumentationTest.java
- src/test/resources/for-parsing-and-compilation/doc.golo
- markdown titles can be added into the documentations
- add highlight.js
- tweak the CSS
- change the way internal links are computed
- update the doc of gololang modules
> Improve golodoc

- src/main/java/org/eclipse/golo/runtime/PropertyMethodFinder.java
- src/test/resources/for-execution/unions.golo
> Fix conflict between property and union attribute resolution

- src/main/java/org/eclipse/golo/compiler/JavaBytecodeGenerationGoloIrVisitor.java
- src/main/java/org/eclipse/golo/compiler/ParseTreeToGoloIrVisitor.java
- src/main/java/org/eclipse/golo/compiler/ir/AbstractInvocation.java
- src/main/java/org/eclipse/golo/compiler/ir/Builders.java
- src/main/java/org/eclipse/golo/compiler/ir/Decorator.java
- src/main/java/org/eclipse/golo/compiler/ir/FunctionInvocation.java
- src/main/jjtree/org/eclipse/golo/compiler/parser/Golo.jjt
- src/test/java/org/eclipse/golo/compiler/CompileAndRunTest.java
- src/test/resources/for-execution/decorators.golo
- src/test/resources/for-parsing-and-compilation/method-call.golo
This is a refactoring in order to simplify the anonymous call chains as described in #385 .
> FIX 385: Refactor anonymous call chains

- src/main/golo/errors.golo
- src/main/golo/standard-augmentations.golo
- src/main/java/gololang/DynamicObject.java
- src/main/java/gololang/DynamicVariable.java
- src/main/java/gololang/FunctionReference.java
- src/main/java/gololang/Predefined.java
- src/main/java/gololang/error/Result.java
- src/main/java/org/eclipse/golo/doc/HtmlProcessor.java
- src/main/java/org/eclipse/golo/doc/MarkdownProcessor.java
- src/main/java/org/eclipse/golo/runtime/TypeMatching.java
- src/test/java/gololang/EvaluationEnvironmentTest.java
- src/test/java/gololang/FunctionReferenceTest.java
- src/test/java/gololang/TemplateEngineTest.java
Clean some debt left behind by previous refactoring and add some useful
methods and augmentations to FunctionReference.
Also fix an undetected bug in `andThen` (we can now compose varargs
functions)
> Code cleaning and small improvements

- doc/dynamic-objects.adoc
- src/main/java/gololang/DynamicObject.java
- src/main/java/gololang/FunctionReference.java
- src/main/java/org/eclipse/golo/runtime/MethodInvocationSupport.java
- src/test/java/gololang/DynamicObjectTest.java
- src/test/java/org/eclipse/golo/compiler/CompileAndRunTest.java
- src/test/resources/for-execution/dynamic-objects.golo
Adds a `kind` attribute that can be used to compare dynamic objects and
in the toString method.
Adds a toString method that display all fields.
> Changes to DynamicObject

- build.gradle
> Compile Java sources with the -parameters flag

- src/main/java/org/eclipse/golo/runtime/OperatorSupport.java
- src/test/java/org/eclipse/golo/runtime/OperatorSupportTest.java
> FIX string multiplication by 0

- samples/dynamic-object-json.golo
- src/main/golo/json.golo
- src/test/java/gololang/JSONTest.java
- src/test/resources/for-test/json.golo
I wrote methods that return a new dynamic object (or an array of dynamic objects) from a JSON string where each level entry is mapped into the dynamic object or an array of dynamic objects.
What I did:
```golo
let obj1 = JSON.toDynamicObjectFromJSONString("""
{
"id":"bob",
"remarks": null,
"friends":[
{"name":"sam"}, {"name":"jane"}, {"name":"john"}
],
"address": {
"street":"20 Avenue Albert Einstein",
"city":"Villeurbanne",
"zip":"69100",
"country":"France"
}
}
""")
println(obj1: friends(): get(2): name(): equals("john")) # true
println(obj1: address(): city(): equals("Villeurbanne")) # true
let obj2 = JSON.toDynamicObjectFromMap(map[
["id", "bob"],
["friends", [
map[["name", "sam"]],
map[["name", "jane"]],
map[["name", "john"]]
]],
["address", map[
["street", "20 Avenue Albert …
```
> Dynamic objects trees from JSON text

- src/main/java/gololang/Predefined.java
- src/test/java/gololang/PredefinedTest.java
For instance
```golo
let s = str("The answer", " is ", 2 * 21)
```
This is functionally equivalent to:
```golo
let s = ["The answer", " is ", 2 * 21]: join("")
```
> Add a predefined function to concatenate strings

- doc/basics.adoc
- src/main/java/gololang/Tuple.java
- src/main/java/gololang/Unknown.java
- src/test/java/gololang/TupleTest.java
The `extend` methods create a new tuple with added values.
> Adds extension methods to Tuple

- src/main/java/gololang/Predefined.java
- src/test/java/gololang/PredefinedTest.java
> Fix arrayTypeOf(byte.class) yields a ClassNotFoundException

- doc/java-interop.adoc
- src/main/java/org/eclipse/golo/runtime/Extractors.java
- src/main/java/org/eclipse/golo/runtime/FunctionCallSupport.java
- src/main/java/org/eclipse/golo/runtime/MethodFinder.java
- src/main/java/org/eclipse/golo/runtime/RegularMethodFinder.java
- src/main/java/org/eclipse/golo/runtime/Warnings.java
- src/main/resources/messages.properties
- src/main/resources/messages_fr_FR.properties
When golo code use a java element marked as deprecated, a warning is
printed.
> Adds deprecation warning

- golo-maven-plugin/src/main/java/org/eclipse/golo/maven/GolodocMojo.java
Quick fix for #502 . Still no tests for the maven plugin :smile:
> Use ModuleDocumentation in maven plugin

- src/main/java/gololang/Predefined.java
- src/main/java/gololang/Runtime.java
- src/main/java/org/eclipse/golo/cli/Main.java
- src/main/java/org/eclipse/golo/cli/command/spi/CliCommand.java
- src/main/java/org/eclipse/golo/compiler/GoloCompiler.java
- src/main/java/org/eclipse/golo/compiler/ParseTreeToGoloIrVisitor.java
- src/main/java/org/eclipse/golo/compiler/ir/GoloModule.java
- src/main/java/org/eclipse/golo/compiler/parser/ASTCompilationUnit.java
- src/main/resources/messages.properties
- src/main/resources/messages_fr_FR.properties
This module provides functions to interact with the golo runtime
environment.
> Adds a `gololang.Runtime` module

- doc/predefined-functions.adoc
- src/main/java/gololang/EvaluationEnvironment.java
- src/main/java/gololang/IO.java
- src/main/java/gololang/Predefined.java
- src/main/java/gololang/Runtime.java
- src/main/java/org/eclipse/golo/cli/command/ProjectInitializer.java
- src/main/java/org/eclipse/golo/doc/AbstractProcessor.java
- src/main/java/org/eclipse/golo/doc/CtagsProcessor.java
- src/main/java/org/eclipse/golo/doc/HtmlProcessor.java
- src/main/java/org/eclipse/golo/doc/MarkdownProcessor.java
- src/test/java/gololang/IOTest.java
- src/test/java/gololang/PredefinedTest.java
- src/test/java/org/eclipse/golo/doc/DocumentationRenderingTest.java
- move file-related functions from `Predefined` to `IO` (deprecated versions in `Predefined` delegate to `IO`)
- add some PrintStream utils.
> Adds an IO module

- tutorials/README.md
- tutorials/build-golo.md
- tutorials/resources/build-golo/cloud-init.yaml
- tutorials/resources/build-golo/create-vm.sh
First Golo tutorial: how to build a Golo distribution from a multipass VM
Related issue https://github.com/eclipse/golo-lang/issues/548
> 📝 add first tutorial: building golo

- src/main/java/gololang/ir/Block.java
- src/main/java/gololang/ir/TryCatchFinally.java
- src/main/java/org/eclipse/golo/compiler/JavaBytecodeGenerationGoloIrVisitor.java
- src/main/java/org/eclipse/golo/compiler/JavaBytecodeUtils.java
- src/test/java/org/eclipse/golo/compiler/CompileAndRunTest.java
- src/test/resources/for-execution/nested-try.golo
> Fix nested try

- src/main/java/gololang/ir/FunctionInvocation.java
- src/main/java/gololang/ir/GoloFunction.java
- src/main/java/org/eclipse/golo/compiler/JavaBytecodeGenerationGoloIrVisitor.java
Refactor the bytecode generation visitor to ease fixing #568 (among other things)
> Refactor bytecode generation

- src/main/java/gololang/ir/Block.java
- src/main/java/gololang/ir/LocalReference.java
- src/main/java/gololang/ir/TryCatchFinally.java
- src/main/java/org/eclipse/golo/compiler/ClosureCaptureGoloIrVisitor.java
- src/main/java/org/eclipse/golo/compiler/JavaBytecodeGenerationGoloIrVisitor.java
- src/main/java/org/eclipse/golo/compiler/JavaBytecodeUtils.java
- src/main/java/org/eclipse/golo/compiler/LocalReferenceAssignmentAndVerificationVisitor.java
- src/main/java/org/eclipse/golo/compiler/SugarExpansionVisitor.java
- src/test/java/org/eclipse/golo/compiler/CompileAndRunTest.java
- src/test/resources/for-execution/return-in-try.golo
> FIX: return in try skips finally

- .gitpod.Dockerfile
- .gitpod.yml
This PR adds GitPod support to the Golo project in order to simplify the setup of a Golo development environment.
See the description in this issue: #572 
- Create a GitPod account by login with your :octocat: handle https://gitpod.io/login/
- For a better user experience, install the GitPod extension for your browser https://www.gitpod.io/docs/browser-extension/
- Select the feature branch related to this PR: `feature-add-gitpod-support` and click on <kbd>Gitpod</kbd>
- Wait for a moment when creating the workspace (the next time will be faster)
Once the GitPod IDE, in the terminal panel, type the below commands:
> building Golo
```
./gradlew installDist
```
> check
```
golo version
golo golo --files samples/dynamic-object-person.golo 
```
You should get this:
```
3.4.0-SNAPSHOT
Mr Bean …
```
> Add GitPod support
